---
- hosts: all
  become: yes
  tasks:
  - name: Installing & updating apache2 package
    apt:
      name: apache2
      state: present
      update_cache: yes
    notify:
    - Restart apache2
    when: ansible_os_family == "Debian"
  - name: Install httpd
    yum:
      name: httpd
      state: present
      update_cache: yes
    notify:
    - Restart httpd
    when: ansible_os_family == "Redhat"
  - name: Install php packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
    notify:
    - Restart apache2
    when: ansible_os_family == "Debian"
  - name: Install php packages in yum
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
    notify:
    - Restart httpd
    when: ansible_os_family == "Redhat"
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
  - name: Restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "Redhat" 
