---
- hosts: webservers
  become: true
  tasks:
  - name: Install or Verify Java 8 is installed
    apt:
      name: default-jdk
      state: latest
      update_cache: yes
  - name: Download tomcat 
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz
      dest: /tmp/
  - name: Create /opt/tomcat
    file:
      path: /opt/tomcat
      state: directory
  - name: Copy tomcat to /opt/tomcat
    copy:
      src: /tmp/apache-tomcat-9.0.8.tar.gz
      dest: /opt/tomcat/apache-tomcat-9.0.8.tar.gz
  - name: unarchive tomcat
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.8.tar.gz
      dest: /opt/tomcat
  - name: Create a Tomcat user
    user:
      name: tomcat